export enum ItemGroup {
    PRIMARY = 'Primary',
    SECONDARY = 'Secondary',
  }
  
  export interface Item {
    id: number;
    name: string;
    group: ItemGroup;
    created_at: string;
    updated_at: string;
  }
  
  // Interface for data when creating a new Item (ID and timestamps are generated by backend)
  export interface CreateItemPayload {
    name: string;
    group: ItemGroup;
  }
  
  // Interface for data when partially updating an Item
  export interface UpdateItemPayload {
    name?: string; // Optional because it's a partial update
    group?: ItemGroup; // Optional
  }
  
  // Interface for the paginated response from the API list endpoint
  export interface PaginatedResponse<T> {
    count: number;
    next: string | null;
    previous: string | null;
    results: T[];
  }