// frontend/src/types.ts

// Enum for Item Groups (matches your Django model's Group choices)
export enum ItemGroup {
    PRIMARY = 'Primary',
    SECONDARY = 'Secondary',
  }
  
  // Interface for an Item as received from the API (includes ID and timestamps)
  export interface Item {
    id: number;
    name: string;
    group: ItemGroup; // Using our enum here for type safety
    created_at: string; // ISO 8601 string (e.g., "2023-10-27T10:00:00Z")
    updated_at: string; // ISO 8601 string
  }
  
  // Interface for data when creating a new Item (ID and timestamps are generated by backend)
  export interface CreateItemPayload {
    name: string;
    group: ItemGroup;
  }
  
  // Interface for data when partially updating an Item
  export interface UpdateItemPayload {
    name?: string; // Optional because it's a partial update
    group?: ItemGroup; // Optional
  }
  
  // Interface for the paginated response from the API list endpoint
  // Matches DRF's PageNumberPagination default structure
  export interface PaginatedResponse<T> {
    count: number;
    next: string | null;
    previous: string | null;
    results: T[]; // Array of your data type (e.g., Item[])
  }